server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://116.62.13.6:3306/chat_project?serverTimezone=GMT%2B8
    username: mercer
    password: Justmyself957!
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 120000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    port: 6379
    password: Justmyself957!
    host: 116.62.13.6
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000
      shutdown-timeout: 100

  thymeleaf:
    enabled: true
    check-template-location: true
    encoding: UTF-8
    excluded-view-names:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  rabbitmq:
    host: 116.62.13.6
    port: 5672
    username: mercerjr
    password: Justmyself957!

#  mvc:
#    view:
#      prefix: classpath:/templates/
#      suffix: .html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
